services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        value: postgres://user:pass@your-db-url:5432/dbname  # Replace with your DB URL
      - key: SECRET_KEY
        generateValue: true
    plan: free